ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS rating_type VARCHAR(10) NOT NULL DEFAULT 'rapid';
ALTER TABLE tournament_players ADD COLUMN IF NOT EXISTS wins INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tournament_players ADD COLUMN IF NOT EXISTS place INTEGER;
